### ISSUE TITLE
Error when downloading RFCs

### ISSUE THREAD

**Issue by zellyn** [monsieurh/rfc_reader#8]
(Installed via `pip install rfc_reader`)

```
~ rfc
No RFC documents found, downloading full archive from IETF site...
Downloading: RFC-all.tar.gz Bytes: 167167918
Traceback (most recent call last):
  File "/usr/local/bin/rfc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 281, in main
    app = RFCApp(pager)
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 227, in __init__
    self._update_docs()
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 251, in _update_docs
    downloader.update()
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 88, in update
    self._update_index(full_path)
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 95, in _update_index
    self._download_file(self.RFC_INDEX, full_path)
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 119, in _download_file
    file_size = RFCDownloader._find_content_len(meta)
  File "/usr/local/lib/python2.7/site-packages/rfc/rfc.py", line 154, in _find_content_len
    file_size = int(meta.getheaders("Content-Length")[0])
IndexError: list index out of range
```

Same error when using `--update`. Appears to leave `rfc_reader` in a state where it thinks it doesn't need to download RFCs, but `-k anything` returns no results.

Directly opening an RFC works: eg. `rfc 7539` will open the chacha20 RFC.

**Comment by monsieurh** [comment]
What version do you have : i.e. what is the output of `rfc --version`

**Comment by zellyn** [comment]
`rfc 0.9`
